apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    url: http://influxdb:8086
    access: proxy
    isDefault: true
    database: quai
    user: user
    secureJsonData:
      password: password
    editable: true

