{
 "title": "Go-quai Metrics Under Development",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Internal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(StateTimes{label=~\".*\"}[1m])",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Transaction slots used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TxpoolGauges{label=\"slots\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locals",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TxpoolGauges{label=\"local\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "rate(TxpoolGauges{label=~\"slots|local\"}[1m])",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Gapped",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TxpoolGauges{label=\"queued\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TxpoolGauges{label=\"pending\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Counters",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(MessageCounters{label=~\".*\"}[1m])",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Transaction Processing",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(TxpoolGauges{label!~\"queued|pending|slots|local\"}[1m])",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "LibP2P Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "expr": "StreamGauges", "legendFormat": "{{label}}" },
    { "expr": "PeerGauges", "legendFormat": "{{label}}" }
   ]
  },
  {
   "title": "Transaction Propagation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "targets": [
    { "expr": "rate(TxPropagation[1m])", "legendFormat": "{{label}}" }
   ]
  },
  {
   "title": "Work Propagation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "rate(WorkObjectCounters[1m])", "legendFormat": "{{label}}" }
   ]
  },
  { "title": "System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Usage System vs Go-quai",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "cpu_usage{usage_type=\"Go-quai\"}",
     "legendFormat": "{{usage_type}}"
    },
    {
     "expr": "cpu_usage{usage_type=\"System\"}",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "I/O Wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "cpu_usage{usage_type=\"Iowait\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": " RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mem_usage{usage_type=\"Stack\"}",
     "legendFormat": "{{usage_type}}"
    },
    {
     "expr": "mem_usage{usage_type=\"Used\"}",
     "legendFormat": "{{usage_type}}"
    },
    {
     "expr": "mem_usage{usage_type=\"Swap\"}",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  {
   "title": "Disk IO/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "disk_usage{usage_type!=\"Iops\"}",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  {
   "title": "Number of IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "disk_usage{usage_type=\"Iops\"}",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  {
   "title": "Number of Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    { "expr": "net_usage", "legendFormat": "{{net_type}}" }
   ]
  }
 ]
}